on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cherylchen
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Deploy to gh pages
        run: ng deploy
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}